# Generated by Django 5.1 on 2024-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('release_date', models.DateField()),
                ('label', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
    ]
