# Generated by Django 5.1 on 2024-08-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonicwave', '0002_alter_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
